spring.application.name=sample-app
server.port=8385
server.servlet.context-path=/sample-app

server.error.include-message=always

spring.datasource.url=jdbc:postgresql://localhost:5432/STUDENT_INFORMATION_DB
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

spring.jpa.properties.hibernate.transaction.coordinator_class=jdbc
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.writer-with-order-by-keys=true



jwt.accessTokenValiditySeconds=86400

client.secret=9d0C51%VbI*b5xVs6I*h
request.read.timeout=60000
request.connect.timeout=60000

spring.profiles.active=DATABASE